volumes:
  db-data: {}
  web-data: {}

services:
  db:
    image: postgres:17
    container_name: postgres_db
    restart: always
    ports:
      - "5444:5432"
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      # Create project db user, project db and give privileges to the user on the db
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  odoo:
    image: odoo:18.0
    container_name: odoo_app
    restart: always
    ports:
      - "8069:8069"
    env_file:
      - .env
    volumes:
      - web-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    depends_on:
      - db
    command: ["-i", "base", "-d", "${PROJECT_DB}"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069"]
      interval: 15s
      timeout: 10s
      retries: 5
